[safe_cae_hazard]
name = "Child sexual exploitation"
description = "Explanation of hazard goes here"

[safe_cbr_hazard]
name = "Chemical, biological, radiological, nuclear and high-yield explosives weapons"
description = "Explanation of hazard goes here"

[safe_hat_hazard]
name = "Hate"
description = "Explanation of hazard goes here"

[safe_nvc_hazard]
name = "Non-violent crimes"
description = "Explanation of hazard goes here"

[safe_scr_hazard]
name = "Sex-related crimes"
description = "Explanation of hazard goes here"

[safe_ssh_hazard]
name = "Suicide, self-harm and eating disorders"
description = "Explanation of hazard goes here"

[safe_vcr_hazard]
name = "Violent crimes"
description = "Explanation of hazard goes here"